name: Add new mod / edit existing mod
description: Request for a new mod to be added to the database, or edit an existing mod.
title: "[Your mod name here]"
labels: ["add-mod"]
body:
  - type: input
    id: uniqueName
    attributes:
      label: Mod uniqueName
      description: "Your mod's ID, unchangeable and unique within the whole database. IMPORTANT: must match uniqueName from your mod's `manifest.json`. If you're editing an existing mod, this must match the `uniqueName` of that mod. This property can't be edited."
      placeholder: LaymGlitched.ThorofareModMenu
    validations:
      required: true
  - type: input
    id: name
    attributes:
      label: Mod name
      description: Human-readable title for your mod. If you want to change your mod's name later, you'll need to request a change to the database again.
      placeholder: Thorofare Mod Menu
    validations:
      required: true
  - type: input
    id: repoUrl
    attributes:
      label: GitHub repository URL
      description: GitHub repository that contains the mod's source code and releases.
      placeholder: https://github.com/...
    validations:
      required: true
  - type: dropdown
    id: tags
    validations:
      required: true
    attributes:
      label: Tags
      description: Tags describe your mod and make it easier for users to find it. You can select multiple.
      multiple: true
      options:
        # These options have to match the ones defined in mods.schema.json
        - jam
        - library
        - gameplay
        - tweaks
        - integration
        - tool
        - content
        - story
        - audiovisual
        - localization
  - type: input
    id: authorDisplay
    attributes:
      label: Author display name
      description: Custom name to show in the author field for this mod. Useful if your mod is in an organization, or made by multiple people. Leave blank to use the repository owner name.
      placeholder: LaymGlitched & Yyk
